### ISSUE TITLE
[Docker] Stuck in the basic web-calibre configuration

### ISSUE THREAD

**Issue by Dunhill69** [janeczku/calibre-web#1109]
I am stuck in the basic web-caliber configuration in docker. When in Caliber database location I put the path of where my caliber library (/media/walter/Elements/Books) is, which is an external disk, it returns the following message. Invalid BD location, please enter the correct route. By touching send. What am I doing wrong ?

**Comment by OzzieIsaacs** [comment]
Please ask this question at the docker repro. I don't have any clue about the docker stuff and the container mapping of the folders for the database.  
Sorry

**Comment by MerouaneBen** [comment]
hey @Dunhill69 ,

if you're using **linuxserver** image,  below the docker-compose I'm using, you need to mount your library inside `/books` in the container.

```
version: "3"
services:
  calibre:
    image: linuxserver/calibre-web
    container_name: calibre
    hostname: caliber
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Toronto
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - caliberConfig:/config
      - letsencrypt:/certs
      - /Gmounts/books:/books
    expose:
      - 8083
    restart: unless-stopped
```
