### ISSUE TITLE
Rename title failed with error: No such file or directory

### ISSUE THREAD

**Issue by setevoy2** [janeczku/calibre-web#1112]
I have a Calibre library from a desktop's Calibre, and now it's used by Calibre Web.
When trying to change an author's name - have the following error:

> Rename title from: '/books/Stivien Khokingh/Mir v oriekhovoi skorlupie (102)' to '/books/Stivien Khokingh/Mir v orekhovoi skorlupe (102)' failed with error: [Errno 2] No such file or directory

Another error happens some times - _Directory not empty_:

> Rename author from: '/books/Dzhoshua Foier/Einshtein guliaet po Lune. Nauka i iskusstvo zapominaniia_ (411)' to '/books/Dzhoshua Foer/Einshtein guliaet po Lune. Nauka i iskusstvo zapominaniia_ (411)' failed with error: [Errno 39] Directory not empty

Calibre is running as a Docker Container from the _technosoft2000/calibre-web:v1.3.3_ image and has a library's directory mounted from the host:

```
version: '3'

services:

  calibre-web:
    environment:
      - PUID=33
      - PGID=33
    image: technosoft2000/calibre-web:v1.3.2
    container_name: calibre-web
    ports:
      - 8083:8083
    volumes:
      - /data/nextcloud/app/data/setevoy/files/Books/CALIBRE/:/books
      - /data/calibre/app:/calibre-web/app/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
```

And the directory's content is:

```
# ll /data/nextcloud/app/data/setevoy/files/Books/CALIBRE/ | grep 'Khok'
drwxrwx---  4 www-data www-data    4096 Mar  5  2019 Khokingh Stivien
drwxrwxr-x  4 www-data www-data    4096 Dec 17 17:19 Stiven  Khoking
drwxrwx---  3 www-data www-data    4096 Mar  5  2019 Stivien Khokin
drwxr-xr-x  2 www-data www-data    4096 Dec 20 18:16 Stivien  Khokingh
```

Nothing in logs, just the same message:

> [2019-12-21 07:13:30,434] ERROR {cps.helper:319} Rename title from: /books/Stivien  Khokingh/Mir v oriekhovoi skorlupie (102) to /books/Stivien  Khokingh/Mir v orekhovoi skorlupe (102): [Errno 2] No such file or directory

Is it something from my side?
