### ISSUE TITLE
Overly large margins when reading epub on mobile

### ISSUE THREAD

**Issue by slikts** [janeczku/calibre-web#1526]
Epub reader margins are too large on mobile:
![image](https://user-images.githubusercontent.com/137872/87328470-30777200-c53e-11ea-9641-d0f2cf2ba637.png)

It's unclear why the margins would need to be so large and limit the readable area to a small square in the middle. It seems like an oversight, and I've not found a way to configure it.

The environment is using the current LinuxServer calibre-web image.

**Comment by Donatzsky** [comment]
The problem is that, for some reason, there's lot of special-casing for iOS devices in the CSS.

The code in question starts at line 698 (`/* For iPad portrait layouts only */`) here:
https://github.com/janeczku/calibre-web/blob/master/cps/static/css/main.css

Really not sure why it's been done like this.

**Comment by negativzeroe** [comment]
So can we have the ability to shrink the margins and text size? How would we go about this, turn it into a feature request?

**Comment by OzzieIsaacs** [comment]
> Really not sure why it's been done like this.
Me, too. 2 posibilities: 
A) At some point in time I added it based on my iPad layout at that time
B) It was part of the epub reader package and just was copied.

Feel free to change it

**Comment by OzzieIsaacs** [comment]
One remark: There is a request about to small text sizes in the reader on kindle, so if you change it, please don't just change the size, but make it adjustable

**Comment by negativzeroe** [comment]
I don't mind adjusting, IMHO it should be in the ui config section of the admin panel, hence the thought of turning it into a feature request. But I can't find it in the file system in the container or I'd map it and adjust there.

**Comment by zoenglinghou** [comment]
I do not think this is a CSS-only issue. By messing around the stylesheet (using userstyles), It seems that we need to adjust the embedded content inside the iframe as well, otherwise the content would stubbornly stays at a small frame. See for yourself:

```css
@-moz-document regexp("^https://<your-website-here>/read/.*") {
    @media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (orientation: portrait) {
        #viewer {
            width: 80% !important;
            height: 85% !important;
        }

        #viewer iframe {
            width: 80vw !important;
            height: 100% !important;
        }
        
        div.epub-view {
            height: 85vh !important;
        }
    }
}
```
