### ISSUE TITLE
Option to disable animation in caliBlur / add custom CSS in general

### ISSUE THREAD

**Issue by sohnemann** [janeczku/calibre-web#1575]
First, please let me thank you for this amazing piece of software!

**Is your feature request related to a problem? Please describe.**
For me the fade-in animation in caliBlur is way too slow. 
It just feels sluggish and not snappy.

**Describe the solution you'd like**
I would like to disable the animation entirely. 
If that's via an option in the settings menu or via a textfield allowing custom CSS.

**Describe alternatives you've considered**
I've considered using GreaseMonkey / TamperMonkey. 
But that would be an ugly solution.

**Additional context**
Here is the used CSS (caliBlur.min.css),
showing the animation being set to 1 second:

```css
body.blur .row-fluid .col-sm-10 {
    -webkit-animation: fadeIn 1s linear 1;
    animation: fadeIn 1s linear 1
}
```
