### ISSUE TITLE
Kobo sync over SSL proxy

### ISSUE THREAD

**Issue by ymoona** [janeczku/calibre-web#1764]
Hi I'm trying to setup kobo sync of ssl. 

I run calibre-web with ssl from a container (https://registry.hub.docker.com/r/linuxserver/calibre-web/) on Synology
I then use nginx to expose the service with SSL. This works great for the webapp itself, but sync does not work. 

The documentation on how setup and debug is quite extensive but I got stuck a thing that I dont fully understand. 

I have updated the reader with my endpoint: 
`api_endpoint=https://[[MyUrl]/kobo/[MyToken]`

Note how I added the https there. 

> [2020-12-19 19:58:41,340] DEBUG {cps.kobo:928} Kobo: Received unproxied request, changed request port to external server port                                                                                                                                                               
[2020-12-19 19:58:41,340] DEBUG {cps.kobo:938} Kobo: Received unproxied request, changed request url to http://[MyUrl]:443                                                                                                                                                         
[2020-12-19 19:58:41,375] DEBUG {cps.kobo:851} Unimplemented User Request received: http://[MyUrl]/kobo/[MyToken]/v1/user/profile                                                                                                                           
[2020-12-19 19:58:41,867] DEBUG {cps.kobo:851} Unimplemented User Request received: http://[MyUrl]/kobo/[MyToken]/v1/user/loyalty/benefits                                                                                                                  
[2020-12-19 19:58:41,980] DEBUG {cps.kobo:851} Unimplemented User Request received: http://[MyUrl]/kobo/[MyToken]/v1/analytics/gettests                                                                                                                     
[2020-12-19 19:58:42,010]  INFO {cps.kobo:130} Kobo library sync request received.                                                                                                                                                                                                          
[2020-12-19 19:58:42,011] DEBUG {cps.kobo:132} Kobo: Received unproxied request, changed request port to external server port      

The requests that get logged show http instead of https. Is there some config that I'm missing?
Now the sync fails on the kobo.

**Comment by ymoona** [comment]
I can confirm that sync does work locally. When I configure the Kobo eReader.conf with the exact link from the "Kobo Sync Token" it does work

**Comment by ymoona** [comment]
Tested a bit more. I removed the SSL force on the proxy host of nginx. This makes it possible to use http instead of https (actually the proxy is now configured for both http and https)
Updated kobo conf to http and sync still wont work. So it seems not an SSL issue but a proxy issue. 


When I with postman do a get on the sync endpoint (by IP, with SSL via proxy and without SSL via proxy), the response is always the same:

> {}

When I do the same on one of the endpoints logged in the calibre-web log( http://192.168.178.201:8083/kobo/[MyToken]/v1/user/profile) I get:
> {
    "ResponseStatus": {
        "ErrorCode": "UnauthorizedAccessException",
        "Message": "Unauthorized Request. Missing authentication token."
    }
}

This is the same as when I go via the proxy (with or without SSL)

**Comment by ymoona** [comment]
I also tried fiddling with the proxy headers, but not sure what to fill in there:
> proxy_set_header Host  $server;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

did at least not help

**Comment by lorenzschmid** [comment]
As far as I understood calibre-web implements only a subset of the API of storeapi.kobo.com. So it is completely normal that calling `https://[[MyUrl]/kobo/[MyToken]` returns `{}`. What happens if you call an API endpoint which is actually serviced by calibre-web such as `https://[[MyUrl]/kobo/[MyToken]/v1/library/sync`?

**Comment by downey-lv** [comment]
Just wanted to add that that I was experiencing an issue with HTTPS requests as well - sync worked but images and books themselves couldn't be downloaded. 
Kobo requested the books in HTTP, but proxy redirected it to HTTPS for the download so Kobo just threw an error
`Nov 17 23:48:26 nickel: (  3261.129 @ 0x1b638c8 / packetdump.warning) "http://[MyUrl]/kobo/[MyToken]/download/5401/kepub" => "Connection closed" `
Once I moved the API to HTTP, everything worked fine

**Comment by jmlgo** [comment]
for some reason covers and books will be downloaded using plain HTTP (well done rakuten, well done). HTTPS for web interface and the rest of the API must be enabled, but HTTPS redirection should be disabled in the proxy, and  'Server External Port' parameter of calibre-web must be configured with the plain HTTP port of the proxy (usually 80).

**Comment by daveallie** [comment]
I came across this same issue, there's a quick and dirty way to trick calibre-web into thinking it's proxied and returning the correct urls.

For reference my setup is:
- calibre-web docker container running on a host
- Docker configuration mapping port 8083 (will also work for an) on the host to port 8083 in the container
- nginx setup to terminate SSL and proxy the connection to port 8083

I noticed that `is_proxied` is only set to true if at least one of `X-Script-Name`, `X-Scheme`, or `X-Forwarded-Host` headers are supplied: https://github.com/janeczku/calibre-web/blob/1be7dfcdca7a3c9be08387dfa795f1d565ed266e/cps/reverseproxy.py#L62-L79

In my case, I only had:
```
    proxy_pass              http://localhost:8083;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto https;
    proxy_set_header        Host $http_host;
```

I had to set all three of these headers for it to correctly return  the valid scheme, host, and port

```
    proxy_pass              http://localhost:8083;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto https;
    proxy_set_header        Host $http_host;
    proxy_set_header        X-Scheme https;
    proxy_set_header        X-Script-Name /;
```

Previously the download URLs were local addresses to my docker host, but now they have the full proxied url.

![CleanShot 2022-02-19 at 14 45 06@2x](https://user-images.githubusercontent.com/968573/154786999-0038e2c5-a5ca-4375-81cb-4768b53da735.png)

**Comment by daveallie** [comment]
That being said, my syncing is still failing on the actual device, and while it thinks about it for a while, the books are not downloading 😔

**Comment by jcosmao** [comment]
If it can help those using traefik with ssl, here is my working conf:

# traefik.toml
```
[entryPoints]
  [entryPoints.websecure]
    address = ":443"
    # X-Forwarded-Proto, ...
    [entryPoints.websecure.forwardedHeaders]
      insecure = true
```

# docker-compose.yaml
```
---
version: "3"
services:
  calibre-web:
    ...
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.http.routers.calibre.service=calibre"
      - "traefik.http.routers.calibre.rule=Host(`$FQDN`)"
      - "traefik.http.routers.calibre.entrypoints=websecure"
      - "traefik.http.routers.calibre.tls=true"
      - "traefik.http.routers.calibre.tls.certresolver=lets-encrypt"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"
      - "traefik.backend=calibre"
      - "traefik.frontend.rule=Host(`$FQDN`)"
      - "traefik.frontend.passHostHeader=true"
      # Add X-Scheme: https  header => url generated by calibre-web will used https://
      - "traefik.http.middlewares.customheader.headers.customrequestheaders.X-Scheme=https"
      - "traefik.http.routers.calibre.middlewares=customheader"
```

**Comment by MrHappy** [comment]
For HAProxy I used the following (do not know if it is overcomplete, but it works for me):
```
backend bk_calibre-web
        mode http
        option forwardfor
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        http-request set-header X-Scheme https if { ssl_fc }
        http-request set-header X-Script-Name /
        server calibre-web <ipaddress>:8083 check
```

**Comment by rs-gh-asdf** [comment]
# (Mostly) Working Configuration
I have a Kobo Libra 2 running software version 4.34.20097. I **am able** to sync books over an SSL-forced proxy using the latest calibre-web from pypi:
```
# cps --version
Calibre-Web version: 0.6.19 - unknown git-clone
```
I am using Nginx (default Ubuntu 20.04 version) to force the reverse SSL reverse proxy:
```
# nginx -V
nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-7KvRN5/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-compat --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module
```
The calibre-web server is running on "bare metal" (this whole thing is a VM, no docker anywhere). Calibre-web lives on a subpath because the root for this VM is another web application. This is my relevant Nginx config portion:
```
server {
    listen 80;
    server_name servername.redacted;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    ssl_certificate /etc/ssl/certs/ssl-cert-letsencrypt.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-letsencrypt.key;
    server_name servername.redacted;
    client_max_body_size 4M;
    client_body_buffer_size 128k;
    root /var/www/html;
    index index.html;
    location /calibre {
        proxy_pass http://127.0.0.1:8083;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Script-Name /calibre;
        client_max_body_size 512m;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }
}
```
And this is my configuration for calibre-web:
![image](https://user-images.githubusercontent.com/105696616/197446077-6947c87a-0b9c-4a4b-8a93-a1a8b7d13685.png)
(Kobo Sync enabled, Proxy unknown requests to Kobo Store enabled, Server External Port 80)

It seems, based on my testing, that sometimes I am able to get covers and sometimes I am not. I am not sure what the cause of this is, but I am at least able to sync books added to my shelf. I spend very little time looking at the cover of the book when compared to the amount of time that I spend looking at the contents. I hope that this helps somebody. It seems that it is in fact possible to force SSL and still get your ebooks.

**Comment by alex3305** [comment]
Working configuration for Caddy with Calibre VNC on a subpath:

```
*.example.com {
  @calibre {
    host library.example.com
  }

  handle @calibre {
    handle /calibre/* {
      reverse_proxy calibre-vnc:8080
    }
    reverse_proxy calibre-web:8083 {
      header_up X-Scheme https
    }
  }
}
```

I have this configured through Docker labels with Compose and the excellent [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy):

```yaml
services:
  calibre:
    container_name: calibre
    image: lscr.io/linuxserver/calibre:${CALIBRE_VERSION:-latest}
    restart: on-failure
    security_opt:
      - seccomp:unconfined
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-99}
      PGID: ${PGID:-100}
      UMASK: ${UMASK:-022}
      SUBFOLDER: /calibre/
    networks:
      swarm:
    volumes:
      - ${APPDATA}/calibre:/config
      - ${BOOKS_LIBRARY}:/books
    labels:
      - caddy=*.example.com
      - caddy.@${COMPOSE_PROJECT_NAME}.host=library.example.com
      - caddy.handle=@${COMPOSE_PROJECT_NAME}
      - caddy.handle.handle=/calibre/*
      - caddy.handle.handle.reverse_proxy={{upstreams 8080}}

  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:${CALIBRE_WEB_VERSION:-latest}
    restart: on-failure
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-99}
      PGID: ${PGID:-100}
      UMASK: ${UMASK:-022}
    networks:
      swarm:
    volumes:
      - ${APPDATA}/calibre-web:/config
      - ${BOOKS_LIBRARY}:/books
    depends_on:
      - calibre
    labels:
      - caddy=*.example.com
      - caddy.@${COMPOSE_PROJECT_NAME}.host=library.example.com
      - caddy.handle=@${COMPOSE_PROJECT_NAME}
      - caddy.handle.reverse_proxy={{upstreams 8083}}
      - caddy.handle.reverse_proxy.header_up=X-Scheme https

networks:
  swarm:
    name: swarm
    external: true
```
