### ISSUE TITLE
Fail to upload a ebook

### ISSUE THREAD

**Issue by enefem** [janeczku/calibre-web#1875]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**
1. Go to the main page
2. Click on Upload button
3. Select a pdf file to upload.
4. See error: "could not saved to temp dir"

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

[2021-03-01 15:56:53,630]  INFO {cps.server:216} webserver stop (restart=False)
[2021-03-01 15:56:54,635]  INFO {cps.server:196} Performing shutdown of Calibre-Web
[2021-03-01 15:57:04,124]  INFO {cps:101} Starting Calibre Web...
[2021-03-01 15:57:04,321]  INFO {cps.server:146} Starting Gevent server on [::]:8083
[2021-03-01 15:57:11,435] ERROR {cps.editbooks:813} File ************.pdf could not saved to temp dir

**Expected behavior**
The ebook is uploaded properly

**Comment by OzzieIsaacs** [comment]
During upload the pdf file is stored in the temp dir and afterwards moved to the right location. 
The pdf file in your case can not be saved to the temp dir. Maybe the user is missing access rights. On Windows the usual temp dir is c:\temp
Or maybe there is not enough space left on the hdd to save the pdf file.

**Comment by enefem** [comment]
I'm using the docker calibre-web from linuxserver.
This uploading functionality was working properly before and I have ensured that I have enough disk space in my HD.

**Comment by OzzieIsaacs** [comment]
Please ask for support at the docker repository of calibre-web, I'm not the creator of the docker containers and I don't know whats going wrong, sorry

**Comment by johnmmcgee** [comment]
Had this issue as well using the linuxserver.io maintained calibre-web container.  It was related to selinux on the container while using podman.  

Attempting to mv the file from its temp location (/tmp/calibre_web/) to its desired location resulted in the following when doing some test:
`mv: setting attribute 'security.selinux' for 'security.selinux': Permission denied`

I went ahead and disabled selinux on the container itself,  and this resolved the issue.  

`--security-opt label:disable`

Not sure if there is a better fix, but i was trying to figure this out last night, and came across this post.  Perhaps this will help someone else along the way.

**Comment by slogemann1** [comment]
In case it could still help anyone:

I recently had the same issue using the docker image. When I looked into it I saw that the error reported was due to not having enough space in the temp directory. It could be solved by mounting ```/tmp``` as a separate volume on disk instead of within the container itself. I made sure that the volume had the same permissions as the ```/tmp``` directory on the image.

Here is my docker compose file:
```
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.26
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    volumes:
      - /srv/calibre-web/config:/config
      - /srv/calibre-web/library:/books
      - /srv/calibre-web/temp:/tmp                      
    ports:
      - 8083:8083
    restart: unless-stopped
```

And the temp folder with permissions:
```
drwxrwxrwt  3 root      root        3 Aug 24 17:12 temp
```
