### ISSUE TITLE
Mixed content issues running behind Traefik 1.7 and Organizr

### ISSUE THREAD

**Issue by joe-eklund** [janeczku/calibre-web#2054]
**Describe the bug/problem**
Hello. I have Calibre-Web running in docker behind Traefik 1.7 proxy (still yet to upgrade to 2.x) and iframing it in Organizr. It loads, but when I try to search or login I get this error:

```
Mixed Content: The page at 'https://my_domain.com/#Calibre' was loaded over HTTPS, but requested an insecure resource 'http://calibre-web.my-domain.com/login?next=%2Fme'. This request has been blocked; the content must be served over HTTPS.
```

**Expected behavior**
Search, Login, etc. all work correctly inside an iframe behind organizr and traefik 1.7.

**Environment (please complete the following information):**
 - OS: Linux 4.15.0-147-generic Ubuntu
 - Python version: 3.8.5
 - Calibre-Web version:0.6.12 - 54d06e580d73ba58274e7ed4efbd8fc94b7e1856
 - Docker container: LinuxServer
 - Special Hardware: N/A
 - Browser: Version 91.0.4472.124 (Official Build) (64-bit)

**Additional context**

Here is my docker-compose where you can see I am setting the X-SCHEME header, which based on my research from other issues (seems to be a common problem - but I haven't found anything with my exact setup of Traefik 1.7 and Organizr), _should_ be fixing my issue, but doesn't seem to be. The frame ancestors header I am adding does get it to partially load, but I'm still having problems with getting all requests to be sent over https instead of http. Any help in this would be much appreciated. Thanks!

```
  calibre_web:
    image: linuxserver/calibre-web
    container_name: calibre_web
    restart: unless-stopped
    networks:
      - traefik_proxy
      - calibre_web_internal
    ports:
      - 8085:8083
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - linuxserver/calibre-web:calibre # Used for ebook conversion
    volumes:
      - /home/my_user/calibre_web/config:/config
    labels:
      - traefik.calibre_web.frontend.rule=Host:calibre-web.my_domain.com
      - traefik.calibre_web.frontend.auth.forward.address=http://organizr_v2/api/v2/auth?group=4
      - traefik.calibre_web.frontend.headers.customRequestHeaders=X-SCHEME https
      - traefik.calibre_web.frontend.headers.contentSecurityPolicy=frame-ancestors https://my_domain.com
      - traefik.backend=calibre_web
      - traefik.docker.network=traefik_proxy
      - traefik.port=8083
```

**Comment by joe-eklund** [comment]
I have upgraded to Traefik 2 and am still running into the same mixed content error while in an iframe. When I browse to the subdomain directly, the behavior works as expected. I do see that the original requests are getting answered with an `HTTP 307`. It then sends the requests again over https and gets a 200 and everything works.

But it's still broken in iframe.

**Comment by joe-eklund** [comment]
I fixed it by adding this header:

```
"traefik.http.middlewares.calibre_web_headers.headers.customrequestheaders.X-SCHEME=https"
```

**Comment by dvdgsng** [comment]
Just ran into this. This works for me with traefik 1.7: `traefik.frontend.headers.customRequestHeaders=X-SCHEME:https` ([related doc](https://doc.traefik.io/traefik/v1.7/configuration/backends/docker/#custom-headers))

**Comment by Sithlord82** [comment]
Where are you putting that line? No matter what I'm doing I cant get it to allow my calibre-web in iframe. Im thinking I might need to specify the cloudflare IPs as being allowed to set the forwardedHeaders but cant get it to work

**Comment by joe-eklund** [comment]
@Sithlord82 What does your docker-comose file look like? And you are using Traefik 2 or Traefik 1?

**Comment by Sithlord82** [comment]
Using Traefik 2. This is what I've got for Traefik

https://pastebin.com/Bc9d3Rvs

and calibre-web

https://pastebin.com/hPymB7dj

**Comment by joe-eklund** [comment]
Ah ok. I put that line in the labels section for Calibre Web and then added that middleware as well. So here is my docker-compose for calibre-web:

```
  calibre_web:
    image: linuxserver/calibre-web
    container_name: calibre_web
    restart: unless-stopped
    networks:
      - traefik_v2_proxy
      - calibre_web_internal
    ports:
      - 8085:8083
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - linuxserver/calibre-web:calibre # Used for ebook conversion
    volumes:
      - /calibre_web/config:/config
      - /books:/books
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_v2_proxy
      - traefik.http.routers.calibre_web.entrypoints=https
      - traefik.http.routers.calibre_web.rule=Host(`calibre-web.my_domain.com`)
      - traefik.http.routers.calibre_web.tls=true

      - traefik.http.services.calibre-web-service.loadbalancer.server.port=8083

      - "traefik.http.middlewares.calibre_websts.headers.contentSecurityPolicy=frame-ancestors my_domain.com"
      - "traefik.http.middlewares.calibre_websts.headers.customFrameOptionsValue=allow-from https://*.my_domain.com"
      - "traefik.http.middlewares.calibre_websts.headers.customrequestheaders.X-SCHEME=https"
      - traefik.http.middlewares.calibre_websts.headers.stsincludesubdomains=true
      - traefik.http.middlewares.calibre_websts.headers.stspreload=true
      - traefik.http.middlewares.calibre_websts.headers.stsseconds=31536000
      - traefik.http.middlewares.calibre_websts.headers.forceSTSHeader=true
      - traefik.http.middlewares.calibre_web-auth.forwardauth.address=http://organizr_v2/api/v2/auth?group=4
      - traefik.http.middlewares.calibre_web-auth2.digestauth.users=user:traefik:encoded_pass
      - "traefik.http.routers.calibre_web.middlewares=calibre_web-auth, calibre_websts"
```

Does doing something like the above work for you?
