### ISSUE TITLE
Send to Kindle button missing

### ISSUE THREAD

**Issue by lenaxia** [janeczku/calibre-web#2067]
**Describe the bug/problem**
I've tried searching and can't find anything, but my Send to Kindle button does not show up anywhere. What do I need to get Send to Kindle working? I've have Calibre Web in front of Calibre server and have smtp emails working. I also have defined a kindle email address for the user.

I have a download and read in browser button but no Kindle button.

```
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
    volumes:
      - $DOCKERDIR/calibre/server:/config
      - $DOCKERDIR/calibre/library:/library
    #  - $DOCKERDIR/calibre/incoming:/incoming
    ports:
      - 8090:8080
      - 8091:8081
    restart: unless-stopped

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - $DOCKERDIR/calibre/web:/config
      - $DOCKERDIR/calibre/library:/library
    ports:
      - 8093:8083
    restart: unless-stopped
    networks:
      - medianet
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.calibreweb-rtr.entrypoints=https"
      - "traefik.http.routers.calibreweb-rtr.rule=Host(`library.$DOMAINMIKEGOESONLINE`)"
      - "traefik.http.routers.calibreweb-rtr.tls=true"
      - "traefik.http.routers.calibreweb-rtr.priority=90"
      ## Middlewares
      - "traefik.http.routers.calibreweb-rtr.middlewares=chain-authelia-mikegoesonline@file"
      ## HTTP Services
      - "traefik.http.routers.calibreweb-rtr.service=calibreweb-svc"
      - "traefik.http.services.calibreweb-svc.loadbalancer.server.port=8083"
```
