### ISSUE TITLE
Calibre-Web no longer installs on Ubuntu 22.04 pre-releases, as part of Internet-in-a-Box ("Unable to find pip in the virtualenv")

### ISSUE THREAD

**Issue by holta** [janeczku/calibre-web#2327]
10 days ago Calibre-Web installed successfully on the Ubuntu 22.04 daily build pre-release from that time (as part of [Internet-in-a-Box](https://internet-in-a-box.org)).

In the last week or so however, Calibre-Web is no longer installing, yielding this error:

> TASK [calibre-web : Download Calibre-Web dependencies (using pip) into python3 virtual environment /usr/local/calibre-web-py3] ***
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unable to find pip in the virtualenv, /usr/local/calibre-web-py3, under any of these names: pip3, pip. Make sure pip is present in the virtualenv."}

Here's the [Ansible code](https://github.com/iiab/iiab/blob/master/roles/calibre-web/tasks/install.yml#L45-L50) that's failing:

```
- name: Download Calibre-Web dependencies (using pip) into python3 virtual environment {{ calibreweb_venv_path }}
  pip:
    requirements: "{{ calibreweb_venv_path }}/requirements.txt"
    virtualenv: "{{ calibreweb_venv_path }}"    # /usr/local/calibre-web-py3
    virtualenv_site_packages: no
    virtualenv_command: python3 -m venv {{ calibreweb_venv_path }}
```

Is this possibly due to a change in VENV / PIP within the latest Ubuntu 22.04 pre-releases?

Or is this problem possibly arising from [ansible-core 2.12.3](https://groups.google.com/g/ansible-announce/c/dp-hrpDwD20) &mdash; e.g. if that's what is suddenly no longer able to find pip (or pip3) on Ubuntu 22.04?

CLARIF: Ubuntu 22.04 will be released 2022-04-21 so there are 6 weeks left to resolve this, but it would be really great to understand this and solve this for Ubuntu 22.04's Beta on 2022-03-31, if anybody hopefully has ideas!

Originally reported here:

- https://github.com/iiab/iiab/issues/3130
