### ISSUE TITLE
"Settings database is not writeable." when using local SMB mount inside Docker

### ISSUE THREAD

**Issue by mbirth** [janeczku/calibre-web#2612]
**Describe the bug/problem**

I'm using the [official Docker image](https://hub.docker.com/r/linuxserver/calibre-web) and had Calibre-Web running fine with a normal bind mount, i.e. the compose yml section looked like this:

```
    volumes:
      - /opt/docker/calibre-web:/config
```

Now I've upgraded my home zoo to a Docker Swarm and want to deploy it using a SMB mount of type "local". In the compose file this looks like this:

```
    volumes:
      - smb-calibreweb:/config

...

volumes:
  smb-calibreweb:
    driver_opts:
      type: "smb3"
      device: "//mylocalnas/docker/calibre-web"
      o: "vers=3.1.1,addr=172.16.254.1,username=xxx,password=xxx,uid=1000,gid=1000,cache=loose,iocharset=utf8,noperm,hard"
```

While I can open a shell in that container as user "abc" (=the user with which the Calibre-Web app is run) and happily open/write all the files in that folder, Calibre Web insists that the "Settings database is not writeable.". Copying the `app.db` out of that folder to e.g. `/tmp` and running `python3 cps.py -p /tmp/app.db` works fine. But after copying the same database back to `/config`, I get the dreaded error again.

These kind of SMB mounts work fine with other Docker containers. And I can read/write to files in that folder with all tools/apps but Calibre-Web believes it can't.

**To Reproduce**
1. Setup Docker image
2. Copy everything from the config-volume onto a NAS with SMB
3. Change your Compose file to mount the volume from your NAS

**Logfile**

No log written.

**Expected behavior**

Calibre-Web starting up as usual.

**Environment (please complete the following information):**
 - OS: Docker image on Docker 20.10.12 on a Raspberry Pi 3B running Ubuntu 22.04.1 LTS
 - Python version: 3.10.6 (Docker image)
 - Calibre-Web version: (Docker image, latest)
 - Docker container: LinuxServer.io version

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]
