### ISSUE TITLE
Cache system

### ISSUE THREAD

**Issue by webysther** [janeczku/calibre-web#2789]
**Is your feature request related to a problem? Please describe.**
Slow page loading

**Describe the solution you'd like**
A cache system using LRU or another in Flask or with redis

**Describe alternatives you've considered**
A make a patch for que main page as a sample test when study the code and the load go from 400ms to ~10ms, we need to discuss the invalidation process, like a batch after every minutes or based on new books added...

**Additional context**
The patch done in [web.py](https://github.com/janeczku/calibre-web/pull/2788) works great but is needed decoupling the template logic to random list.

The tests was using a Synology NAS but all books and server was migrated to nvme server (no improvements) and either with tmpfs disk for sqlite of calibre and calibre-web (no improvements). The slow looks very consistent, so after looking in the logic become clear is render time from python side.

Maybe split **entries**, **random**, **pagination** sections to exclusive function to make sure the cache can be optimized and not affect the random (bypass cache always).

Library size: 10k

Before patch:

![image](https://github.com/janeczku/calibre-web/assets/750007/cee0411a-3806-4837-adc6-a83efc7e9835)

After patch:

![image](https://github.com/janeczku/calibre-web/assets/750007/1a1b34b8-b6dc-49d5-ad7a-b05a413c7efe)

**Comment by kevindherdt** [comment]
Sorry for the stupid question but I applied this to my docker-compose and recreated the docker. How do I know if it is effectively applied? 

I am curious to try it out since I am having a lot of problems with very very slow loading of the thumbnails when opening calibre-web. 
Any other ideas how I could improve the performance or caching?

**Comment by webysther** [comment]
Hi @kevindherdt, I start this but you right, don't work, I ended to have the perception that calibre-web using route to every image you slow down no matter what, this fix some things but still not what I what, so, I use my knowledge in varnish to build another thing, I create 4 container, 1 varnish, 1 server and 2 replicas to provide thumb, with this the slow in only for the first request and the other is snap, this solve 90% but in crazy dreams i think to rewrite all the app because is really simple when in dive in, I will put here my docker-compose.yml to help you:

```
version: '3.9'

services:
  varnish:
    image: varnish:6
    container_name: app-book-varnish
    cpuset: '0'
    networks:
      calibre-web:
    env_file: ../calibre-web/.env
    expose:
      - 80
    volumes:
      - "$STORAGE/varnish/default.vcl:/etc/varnish/default.vcl:ro"
    tmpfs:
      - /var/lib/varnish:exec
    depends_on:
      calibre-web:
        condition: service_healthy
    restart: unless-stopped

  calibre-web-cover-1: &calibre-base
    image: lscr.io/linuxserver/calibre-web:0.6.20
    container_name: app-book-cover-1
    cpuset: '1'
    networks:
      calibre-web:
    volumes:
      - "$STORAGE/config:/config"
      - "$STORAGE/cache:/cache:ro"
      - "$STORAGE/patch/cps/web.py:/app/calibre-web/cps/web.py:ro"
      - "$LIBRARY:/calibre:ro"
      - "$LOG:/log"
    env_file: ../calibre-web/.env
    expose:
      - 8083
    healthcheck:
      test: curl --fail http://localhost:8083 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    restart: unless-stopped

  calibre-web-cover-2:
    <<: *calibre-base
    container_name: app-book-cover-2

  calibre-web:
    <<: *calibre-base
    container_name: app-book-web
    volumes:
      - "$STORAGE/config:/config"
      - "$STORAGE/cache:/cache"
      - "$STORAGE/patch/cps/web.py:/app/calibre-web/cps/web.py:ro"
      - "$STORAGE/patch/cps/jinjia.py:/app/calibre-web/cps/jinjia.py:ro"
      - "$LIBRARY:/calibre:ro"
      - "$LOG:/log"
    depends_on:
      calibre-web-cover-1:
        condition: service_healthy
      calibre-web-cover-2:
        condition: service_healthy

networks:
  calibre-web:
    name: calibre-web
```

.env

```
PUID=1026
PGID=101
TZ=Europe/Rome
STORAGE=/volume1/docker/calibre-web
LOG=/volume1/log/docker/calibre-web
CACHE_DIR=/cache
LIBRARY=/volumeUSB2/usbshare/cache/library/books/calibre
VARNISH_SIZE=2G
CACHE=/volumeUSB2/usbshare/cache/docker/calibre-web
```
