### ISSUE TITLE
Database Configuration error

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [janeczku/calibre-web#2947]
I use docker to star up 
docker-compose.yml
```
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./data/config:/config
      - ./data/books:/books
    ports:
      - 8083:8083
    restart: always

```
when I choose Location of Calibre Database ,I got problem.
![image](https://github.com/janeczku/calibre-web/assets/87591236/18abd080-270a-4f26-99d4-1ec1dee37c70)

how to fix this one
