### ISSUE TITLE
Content Security Policy doesn't contain font-src blob:

### ISSUE THREAD

**Issue by lyonzy** [janeczku/calibre-web#3005]
**Describe the bug/problem** 

I have epubs that use fonts from blobs, and the text didn't show (and there were console errors) when it loaded. I fixed it by changing the CSP to allow blob: for fonts (`font-src 'self' data: blob:`). Happy to provide repro instructions and screenshots but hopefully this is a quick one and doesn't need them.

**Environment (please complete the following information):**
LinuxServer container on Kubernetes.

**Additional context**
Here's the Traefik Middleware I used as a workaround:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: csp-middleware
  namespace: calibre-web
spec:
  headers:
    contentSecurityPolicy: "default-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; font-src 'self' data: blob:; img-src 'self' data: blob: https://*; style-src-elem 'self' blob: 'unsafe-inline';"
```
