### ISSUE TITLE
Kobo Sync Books Failing To Sync; "No such file or directory:..." | Proxmox, Docker, NAS

### ISSUE THREAD

**Issue by Outsmart2383** [janeczku/calibre-web#3040]
**My set up**
I'm running Calibre-Web in Docker, on a Debian VM on Proxmox. Books stored on a Synology NAS which is mounted to the VM.

**Describe the bug/problem** 

I have Calibre-Web (and thus Calibre also) up and running, and my books display correctly in Calibre Web. The bookcovers do not (I get "Cover not available"), I'm not bothered by this, but I think it may be related/caused by the same issue.

I have taken all typical steps to get Kobo Sync working, by Enabling it, modifying my Kobo configuration file etc. and when I click Sync on my Kobo, I don't get a failed sync error, the sync completes and the shelf I have created in Calibre-Web appears on my Kobo. However, no books appears.

**Here's what the logs say:**

```
[2024-05-01 16:06:21,062]  INFO {cps.ub:911} 2 sync entries deleted
[2024-05-01 16:06:28,683]  INFO {cps.kobo:1042} Init
[2024-05-01 16:06:30,824]  INFO {cps.kobo:143} Kobo library sync request received.
[2024-05-01 16:06:30,835] ERROR {cps.kobo:456} [Errno 2] No such file or directory: '/db/author/book.epub'
[2024-05-01 16:06:30,835] ERROR {cps.kobo:456} [Errno 2] No such file or directory:'/db/author/book.epub'
[2024-05-01 16:06:30,844] ERROR {cps.kobo:456} [Errno 2] No such file or directory: '/db/author/book.epub'
[2024-05-01 16:06:30,844] ERROR {cps.kobo:456} [Errno 2] No such file or directory: '/db/author/book.epub'
```

I suspect I understand the cause. Calibre-Web is looking for the books in my /db directory. However, they don't exist there. Because I'm using a NAS. More so, when I'm in Calibre-Web, if I click to "download" the EPUB I get an error:
```
Calibre-Web
Error 404
Not Found
```
and the logs display broadly the same error as when trying to sync:
```
[2024-05-01 16:29:58,769] ERROR {cps.helper:953} File not found: /db/author/book.epub
[2024-05-01 16:30:39,473] ERROR {cps.helper:953} File not found: /db/author/book.epub
```

So I suspect the issue probably resides in my Docker Compose, however I'm not sure where to go from here, because I found it very difficult to get Calibre working with my NAS in the first place. Any advice or suggestions would be greatly appreciated:

```
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    network_mode: "service:gluetun"
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - CALIBRE_OVERRIDE_DATABASE_PATH=/db/metadata.db
    volumes:
      - /home/ubuntu/docker/arr-stack/calibre/data:/config
      - /data/calibre/db:/db
      - /data/mnt/books:/books
      - /mnt/arr/Media/Books/eBooks:/mnt/arr/Media/Books/eBooks
    restart: unless-stopped

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /data/calibre/db:/db
      - /home/ubuntu/docker/arr-stack/calibre/calibre-web:/config
      - /mnt/arr/Media/Books/eBooks:/mnt/arr/Media/Books/eBooks
    restart: unless-stopped
    depends_on:
      - calibre
```
