### ISSUE TITLE
Google oAuth redirect_uri mismatch

### ISSUE THREAD

**Issue by bencmeyer** [janeczku/calibre-web#3068]
Error 400: redirect_uri_mismatch

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.

If you're the app developer, register the redirect URI in the Google Cloud Console.
Request details: redirect_uri=http://<redacted>.net/login/google/authorized flowName=GeneralOAuthFlow

**Expected behavior**

redirect_uri should be https, not http

**Environment (please complete the following information):**

 - container: lscr.io/linuxserver/calibre-web
 - container: traefik:2.11.2
 - cloudflare dns and argo tunnel

**Additional context**

I have tried several workarounds to no avail
I have other services running just fine and work as expected
I believe this has to do with how traefik is forcing security headers as listed in ibracorps setup guide
Below is how they are laid out. I have attempted to change the scheme in the individual 'router' but I am not sure it overrides the defaults.

```
http:
  redirections:
    entryPoint:
      to: https
      scheme: https
```
```
securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "strict-origin-when-cross-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
```
