### ISSUE TITLE
book metadata search only works if FLASK_DEBUG env var is set

### ISSUE THREAD

**Issue by ch604** [janeczku/calibre-web#3088]
**Describe the bug/problem** 

I had just finished setting up calibre/calibre-web docker containers, and was attempting to figure out why I was unable to download any metadata for books I added to the server (Search error!!). The logfile was telling me `INFO {flask_wtf.csrf:263} The CSRF token is missing.`, but checking around through code both here and in flask_wtf's repo didn't lead me very far. I attempted selecting just one or a few search engines per #2562, but this made no difference. I tried to increase the debug level, which I was unable to do from the GUI (might be another bug, ought file separately), but I just stopped the container and adjusted the sqlite value for config_log_level to "10" by hand. This led to nothing new as well. A peek through the code (which helped me find the log level numbers) unearthed the FLASK_DEBUG environment variable, which I set to 'true' and restarted the container. This led to everything working perfectly for some reason (including changing the debug level in the gui), but of course, stdout (in the docker container) was plastered with all kinds of unneeded info. I removed the environment variable, and we are back at square one, regardless of the logging settings I add to the sqlite db. I figure that this has to do with the cache_buster somehow, since that's the only other thing touched by FLASK_DEBUG, but I can't see why that would make a difference...

**To Reproduce**

1. deploy linuxserver.io's calibre and calibre-web, connect them to the same calibre database
2. upload a book to either interface
3. attempt to download metadata (failure expected, see below logfile entry)
4. add FLASK_DEBUG=True environment variable to calibre-web container and restart
5. attempt to download metadata (success expected)

**Logfile**

[2024-07-01 00:21:33,854]  INFO {flask_wtf.csrf:263} The CSRF token is missing.

**Expected behavior**

metadata search function regardless of debug level

**Environment (please complete the following information):**

 - OS: ubuntu server 24.04
 - Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
 - Calibre-Web version: 0.6.21 - c45188beb22adc5416bb8fd73fa23bf5270f7759 - 2023-10-21T12:40:32+02:00
 - Docker container: linuxserver.io via portainer with universal-calibre dockermods
 - Special Hardware: none
 - Browser: Brave

**Additional context**
docker-compose file follows. I changed the public port of calibre proper and added the dockermods, but otherwise its a pretty vanilla deployment. the flask_wtf version in this container is 1.1.2.

```
services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1008
      - PGID=1002
      - UMASK=002
      - TZ=America/Detroit
    volumes:
      - /opt/calibre/config:/config
      - /opt/calibre/uploads:/uploads
      - /opt/calibre/plugins:/plugins
      - /home/data/Books:/Calibre_Library
    ports:
      - 9090:8080
      - 9091:8081
    restart: unless-stopped

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1008
      - PGID=1002
      - UMASK=002
      - TZ=America/Detroit
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /opt/calibre/calibre-web:/config
      - /home/data/Books:/books
    restart: unless-stopped
    depends_on:
      - calibre
    ports:
      - 8083:8083
```
