### ISSUE TITLE
Login state isn't keeped

### ISSUE THREAD

**Issue by efirlus** [janeczku/calibre-web#3313]
## Short Notice from the maintainer 

After 6 years of more or less intensive programming on Calibre-Web, I need a break. 
The last few months, maintaining Calibre-Web has felt more like work than a hobby. I felt pressured and teased by people to solve "their" problems and merge PRs for "their" Calibre-Web. 
I have turned off all notifications from Github/Discord and will now concentrate undisturbed on the development of “my” Calibre-Web over the next few weeks/months.  
I will look into the issues and maybe also the PRs from time to time, but don't expect a quick response from me.

Please also have a look at our [Contributing Guidelines](https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md)

**Describe the bug/problem** 

I don't know why, but suddenly login is not maintained, eternally logout and redirected to login page.
even with `rm -rf config && docker compose --force-recreate` and `admin/admin123` too. eternally, redirected.

```
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CALIBRE_WEBROOT=/calibre
    volumes:
      - /opt/docker/config/calibre-web:/config
      - /NAS/samba/Book:/data/media/books
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre-router.rule=Host(`server.domain.name`) && PathPrefix(`/calibre`)
      - traefik.http.routers.calibre-router.entrypoints=websecure
      - traefik.http.routers.calibre-router.tls=true
      - traefik.http.routers.calibre-router.tls.certresolver=cloudflare
      - traefik.http.routers.calibre-router.service=calibre-service
      - traefik.http.services.calibre-service.loadbalancer.server.port=8083
      - traefik.http.middlewares.calibre-stripprefix.stripprefix.prefixes=/calibre
      - traefik.http.middlewares.calibre-headers.headers.customrequestheaders.X-Script-Name=/calibre
      - traefik.http.routers.calibre-router.middlewares=calibre-stripprefix,calibre-headers

networks:
  proxy:
    external: true
```

**To Reproduce**

1. Pull the docker compose like that
2. docker compose up
3. access to `https://server.domain.name/calibre/`
4. login with admin/admin123, and moving any page just one time.
5. login page reappears, and again, and again.

**Logfile**
while cannot access to setting page, I can't get debug logs...
normal logs are below.. as you can see, nothing specific..

[Calibre-Web Log - Pastebin.com](https://pastebin.com/bXxucPMj)

**Expected behavior**

it was worked very well, however, sudden happen for today.
I don't know why... any other containers are just well.

**Screenshots**

**Environment (please complete the following information):**

 - OS: Ubuntu 24.04 server LTS
 - Python version: 3.12
 - Calibre-Web version: linuxserver/calibre-web:latest, installed last week
 - Docker container: linuxserver
 - Special Hardware: dell wyse minipc
 - Browser: tried every browser of mine, desktop firefox, edge, mobile edge, chrome, firefox

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]
