### ISSUE TITLE
message-id causing emails to get bounced

### ISSUE THREAD

**Issue by gregbert42** [janeczku/calibre-web#3356]
**Describe the bug/problem** 

E-mails from calibre-web are being bounced by my relay smtp server. I believe this is due to the formation of the message-id

**To Reproduce**

My postfix smtp is fully configured with STARTTLS on port 587, with proper and validating letsencrypt certificates
When I use another program  - NextCloud - it is able to authentical and send emails

However. when I use calibre-web, it authenticates locally, but the test e-mail is bounced by my relay server: 
status=bounced (host outgoing-alum.mit.edu[18.7.68.33] said: 553 5.0.0 beader hobo (in reply to end of DATA command)

The message-id of the nextcloud message has < > surrounding the id, whereas the calibre-web item does NOT.

**Logfile**

Calibre-web believes the email was sent successfully.
However, i've done a line by line comparison of my systemd journal

The FIRST line in each of the pairs below is the NextCloud-generated log item. the SECOND is the Calibre-web log item. you will see it is identical except for the formation of the message-id. 

Thank you for your review and comments

```
Nextcloud: Apr 05 20:33:48 Fractal.server.com postfix/submission/smtpd[2922448]: connect from c-73-194-23-000.hsd1.ST.comcast.net[73.194.23.000]
Calibre-web: Apr 05 20:44:22 Fractal.server.com postfix/submission/smtpd[2928334]: connect from c-73-194-23-000.hsd1.ST.comcast.net[73.194.23.000]

Nextcloud: Apr 05 20:33:48 Fractal.server.com postfix/submission/smtpd[2922448]: 4ZVYHJ2RH1z26gLB: client=c-73-194-23-000.hsd1.ST.comcast.net[73.194.23.000], sasl_method=LOGIN, sasl_username=username
Calibre-web: Apr 05 20:44:22 Fractal.server.com postfix/submission/smtpd[2928334]: 4ZVYWV6KJVz26gL4: client=c-73-194-23-000.hsd1.ST.comcast.net[73.194.23.000], sasl_method=LOGIN, sasl_username=username

Nextcloud: Apr 05 20:33:48 Fractal.server.com postfix/cleanup[2922547]: 4ZVYHJ2RH1z26gLB: message-id=<09078e856263c445a5b1d358515ba038@alum.mit.edu>
Calibre-web: Apr 05 20:44:22 Fractal.server.com postfix/cleanup[2928341]: 4ZVYWV6KJVz26gL4: message-id=f5972e87-24c3-49eb-8a0b-d7adff11d4ed@alum.mit.edu

Nextcloud: Apr 05 20:33:48 Fractal.server.com postfix/qmgr[2907082]: 4ZVYHJ2RH1z26gLB: from=<username@alum.mit.edu>, size=15772, nrcpt=1 (queue active)
Calibre-web: Apr 05 20:44:22 Fractal.server.com postfix/qmgr[2928228]: 4ZVYWV6KJVz26gL4: from=<username@alum.mit.edu>, size=538, nrcpt=1 (queue active)

Nextcloud: Apr 05 20:33:48 Fractal.server.com postfix/submission/smtpd[2922448]: disconnect from c-73-194-23-000.hsd1.ST.comcast.net[73.194.23.000] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Calibre-web: Apr 05 20:44:22 Fractal.server.com postfix/submission/smtpd[2928334]: disconnect from c-73-194-23-000.hsd1.ST.comcast.net[73.194.23.000] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8

Nextcloud: Apr 05 20:33:49 Fractal.server.com postfix/smtp[2922548]: 4ZVYHJ2RH1z26gLB: to=<username@alum.mit.edu>, relay=outgoing-alum.mit.edu[18.7.68.33]:587, delay=1, delays=0.01/0.01/0.64/0.34, dsn=2.0.0, status=sent (250 2.0.0 5360XmZb027667 Message accepted for delivery)
Calibre-web: Apr 05 20:44:23 Fractal.server.com postfix/smtp[2928342]: 4ZVYWV6KJVz26gL4: to=<username@alum.mit.edu>, relay=outgoing-alum.mit.edu[18.7.68.33]:587, delay=1, delays=0.01/0.01/0.71/0.3, dsn=5.0.0, status=bounced (host outgoing-alum.mit.edu[18.7.68.33] said: 553 5.0.0 beader hobo (in reply to end of DATA command))
```

**Environment (please complete the following information):**

![Image](https://github.com/user-attachments/assets/8e44b5e7-4f38-4fcb-a1c0-3e40f7762f3c)

**Additional context**

docker-compose.yaml

```
 calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    volumes:
      - /home/remote_fs_user/conf/calibre-web/config:/config
      - "/mnt/HDD/Archive/Book Library/:/books"
    ports:
      - 8085:8083
    restart: unless-stopped
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1

```
