### ISSUE TITLE
[REQUEST] - Update a new release to avoid some back and forth over solved problems in nightly

### ISSUE THREAD

**Issue by Forcebyte** [janeczku/calibre-web#3380]
**Describe the bug/problem** 

Today, a good chunk of problems I see on the Calibre-web repsository are due to users whom are basing their deployments off of the automated linux-server Docker setup, https://github.com/linuxserver/docker-calibre-web

Upon having an issue very similar to https://github.com/janeczku/calibre-web/issues/2849 and some other Git issues, I found https://github.com/janeczku/calibre-web/issues/2849#issuecomment-1891089539 - which completely fixes my problem _and_ is already in master, so I wondered why Linux Server was using some older releases

When I look into this, it seems its just due to an [older catchup between November and now for the last release](https://github.com/janeczku/calibre-web/releases/tag/0.6.24), since the LinuxServer repository [pulls from a release and _not_ latest/source](https://github.com/linuxserver/docker-calibre-web/blob/master/Dockerfile#L57) (which is presumed to be the norm), future people are likely to encounter this as well

In short, I'm asking (if possible) to draft a new release to avoid duplicate questions around Kobo sync issues and other items fixed after November of 2024

(also, completely understand that the author is a bit burnt out, I'd be happy to contribute / draft releases and act as a contributor, I can probably automate the CI like i do with some other closed source projects so this isn't much of an issue in the future)

### Note

**for those of you running this on a Kubernetes environment and are experiencing the same 'kobo sync' generic solution and want to still use the LinuxServer builtin repo, please do the following:**

1. Create a configmap with the contents of kobo_sync_status.py, kobo.py, and kobo_auth.py like so
```yaml
# This is because Calibre-Web uses a custom script to sync with Kobo devices.
# The script is not included in the Calibre-Web image, so we need to provide it ourselves.
apiVersion: v1
kind: ConfigMap
metadata:
  name: calibre-web-custom-files
  namespace: calibre-web
data:
  kobo.py: |
    # content of https://github.com/janeczku/calibre-web/blob/master/cps/kobo.py
  kobo_auth.py
    # content of https://github.com/janeczku/calibre-web/blob/master/cps/kobo_auth.py
  kobo_sync_status.py 
    # content of https://github.com/janeczku/calibre-web/blob/master/cps/kobo_sync_status.py
```

2. Using the configmap, create a post-start lifecycle command, replacing the items in the configmap, mount the configmap to a random path, then remember to restart calibre-web on the UI when you hit issues (either due to container restarts or other problems, for now)
```
# Deployment for Calibre-Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  namespace: calibre-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
        - name: calibre-web
          image: linuxserver/calibre-web
          ports:
            - containerPort: 8083  # Default port for Calibre-Web
          volumeMounts:
            # Extra volume mount for custom files in the configmap
            - name: custom-files
              mountPath: /custom-files
          # 'post-start' command to replace the kobo libraries with the ones within the master branch
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - >
                    cp /custom-files/kobo.py /app/calibre-web/cps/kobo.py &&
                    cp /custom-files/kobo_auth.py /app/calibre-web/cps/kobo_auth.py &&
                    cp /custom-files/kobo_sync_status.py /app/calibre-web/cps/kobo_sync_status.py
      volumes:
        # Extra volume mount for custom files in the configmap
        - name: custom-files
          configMap:
            name: calibre-web-custom-files
```
