### ISSUE TITLE
OAuth redirect_uri set to http:// instead of https:// using lscr.io/linuxserver/calibre-web:latest

### ISSUE THREAD

**Issue by dr-froehlich** [janeczku/calibre-web#3386]
Thank you for this wonderful tool!

## Problem
I am trying to login via google or github Oauth. When I click on the github icon to login, I get the error from github "Invalid Rediredt URI" which is understandable, because the url in my browser looks like:

https://github.com/login/oauth/authorize?response_type=code&client_id=<secret_redactec>&redirect_uri=http%3A%2F%2Fcalibre.mydomain.de%2Flogin%2Fgithub%2Fauthorized&state=WG5GC...

Github rejects the URI because it should says "https://cabibre..." not "http://". 

For Googe OAuth I need to look at the firefox network analysis and find:
GET
	https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=<redacted>.apps.googleusercontent.com&redirect_uri=http://calibre.mydomain.de/login/google/authorized&scope=https://www.googleapis.com/auth/userinfo.email&state=gaoKKNZ...

So it seems both OAuth apps are being supplied with an http redirect_uri. When I configure the callback address in Github as http like that:

http://calibre.p5i.de/login/github/authorized/

I get to authorize the user, however, then the process fails beacuse insecure transport is not allowed.

## My setup

This is my docker compose, it runs on a Raspberry Pi 4
```
---
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
      - OAUTHLIB_INSECURE_TRANSPORT=0
    volumes:
      - ./data:/config
      - /media/library:/books
    #ports:
    #  - 8083:8083
    restart: unless-stopped
    networks:
      public:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.entrypoints=http"
      - "traefik.http.routers.calibre.rule=Host(`calibre.mydomain.de`)"
      - "traefik.http.middlewares.calibre-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.calibre.middlewares=calibre-https-redirect"
      - "traefik.http.routers.calibre-secure.entrypoints=https"
      - "traefik.http.routers.calibre-secure.rule=Host(`calibre.mydomain.de`)"
      - "traefik.http.routers.calibre-secure.tls=true"
      - "traefik.http.routers.calibre-secure.service=calibre"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"
      - "traefik.docker.network=public"
networks:
  public:
    external: true
```

For remote access I go through a Cloudflare zerotrust tunnel, however, when my testing has been locally. The container get a let's encrypt certificate for calibre.mydomain.de. Https: access as such works fine, apart form the OAuth login everything works brilliantly.

I tried to use Reverse Proxy Header Name, e.g. X-Forwarded-Preferred-Username, but there was not change whether I used it or not or whatever the entry said. 

If someone has an idea how I can debug this further or hw the redirect_uri is constructed or how I could get it to say https:// I would be very grateful! Thank you!

Peter

#
