### ISSUE TITLE
Metadata popup window size

### ISSUE THREAD

**Issue by sean-trace** [janeczku/calibre-web#833]
The metadata popup window for books with a long description is displayed off the top of the window resulting in the top header information including download buttons not being visible. Tried in Chrome & Firefox with same result. Could a scrollbar be added to the "Description" area?

**Comment by erkandem** [comment]
@sean-trace Above a certain size a pop-up window does get a scroll area. 

However if the description page exceeds the screen size the top part can not be accessed. Within the default theme that effects e.g. the download button.  Ubuntu 18.x firefox, brave

For now, switching to the dark UI from within the admin panel solved the issue for me. The Dark UI has a different page layout. I said "solved"? "avoided"!

**Comment by sean-trace** [comment]
quick change to cps/static/css/upload.css fixed this for me.
```css
@media (min-device-width: 768px) {
    .modal-dialog {
        position: absolute;
        top: 50px;
        left: 50%;
        transform: translate(-50%, 0%) !important;
    }
}
```
