### ISSUE TITLE
Update epub.js to support vertical-rl

### ISSUE THREAD

**Issue by joshuaavalon** [janeczku/calibre-web#852]
Currently, cablire-web

![asd](https://user-images.githubusercontent.com/7152420/54657323-f93cb080-4b03-11e9-8aa9-d29cfba59fb5.png)

Use epub.js v3

![asd2](https://user-images.githubusercontent.com/7152420/54657360-1e312380-4b04-11e9-9322-c0503954ab4b.png)

**Comment by OzzieIsaacs** [comment]
The epub.js is updated. I currently having no epub with rtl(?) text, so I can't test it, from the documentation I think it could be possible, that the reading direction is autodetected. 
Could you please check the newest commit.

**Comment by joshuaavalon** [comment]
I can confirm it is fixed.

For future reference, this can be tested with the following CSS.

```css
.text {
  writing-mode: vertical-rl;
  -epub-writing-mode: vertical-rl;
  -webkit-writing-mode: vertical-rl;
}
```
